### ISSUE TITLE
new --project error

### ISSUE THREAD

**Issue by sukjinkang** [fprime-community/fprime-workshop-led-blinker#2]
Installed correctly, but had this error in red, in the middle. Windows/Ubuntu install:

  ERROR: Command errored out with exit status 1:
   command: /home/maru/MyProject/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7lt72ssz/fprime-fpp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7lt72ssz/fprime-fpp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_cy5aoqc
       cwd: /tmp/pip-install-7lt72ssz/fprime-fpp/
  Complete output (33 lines):
  WARNING: The wheel package is not available.
  WARNING: The wheel package is not available.
  WARNING: The wheel package is not available.
  WARNING: The wheel package is not available.
  /tmp/pip-install-7lt72ssz/fprime-fpp/.eggs/setuptools_scm-7.1.0-py3.8.egg/setuptools_scm/integration.py:28: RuntimeWarning:
  ERROR: setuptools==44.0.0 is used in combination with setuptools_scm>=6.x

  Your build configuration is incomplete and previously worked by accident!
  setuptools_scm requires setuptools>=45

  This happens as setuptools is unable to replace itself when a activated build dependency
  requires a more recent setuptools version
  (it does not respect "setuptools>X" in setup_requires).

  setuptools>=31 is required for setup.cfg metadata support
  setuptools>=42 is required for pyproject.toml configuration support

  Suggested workarounds if applicable:
   - preinstalling build dependencies like setuptools_scm before running setup.py
   - installing setuptools_scm using the system package manager to ensure consistency
   - migrating from the deprecated setup_requires mechanism to pep517/518
     and using a pyproject.toml to declare build dependencies
     which are reliably pre-installed before running the build tools

    warnings.warn(
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for fprime-fpp

**Comment by LeStarch** [comment]
Tracking in F´as it is more than just this tutorial.
