### ISSUE TITLE
Could not find toolchain file for aarch64-linux?

### ISSUE THREAD

**Issue by Daifaizonaldridge** [fprime-community/fprime-workshop-led-blinker#20]
I was doing the led-blinker: running on hardware instructions and I was able to successfully go through most of it with no errors except when I generate aarch64-linux, and I don't know why it can't find the toolchain file? would like suggestions and help, thank you for reading.

![Screenshot 2023-07-12 140238](https://github.com/fprime-community/fprime-workshop-led-blinker/assets/123976724/6a82cf2c-47d2-43e6-84cc-bc1277c5ff16)

**Comment by LeStarch** [comment]
You should use F´ `devel` as it now ships that toolchain.

To update:

```
cd ../fprime
git fetch origin
git checkout origin/devel
```

Feel free to post back here with any other issues.
