### ISSUE TITLE
Duplication in component-implementation-1.md

### ISSUE THREAD

**Issue by dghbarnes** [fprime-community/fprime-workshop-led-blinker#26]
Duplication in instructions under Try it yourself. Steps 1 and 2 of the table instruct you to add events to the component files to log invalid input and record the blinking state. However, we just did this in the lines above. This is a duplication and leads to the assumption that these events also need to be added to the .fpp file, which is both not necessary and will create errors.

[https://github.com/fprime-community/fprime-workshop-led-blinker/blob/main/docs/component-implementation-1.md#try-it-yourself](url)

**Comment by kevin-f-ortega** [comment]
Addressed in https://github.com/fprime-community/fprime-workshop-led-blinker/pull/33
