### ISSUE TITLE
Error in initial-integration.md

### ISSUE THREAD

**Issue by nathancheek** [fprime-community/fprime-workshop-led-blinker#27]
When creating the deployment, `fprime-util` asks this question:
`Add component LedBlinker to led-blinker/project.cmake at end of file (yes/no)? `

The tutorial says "Use the default response" but there is no default response, that question requires an explicit `yes` to be provided: https://github.com/fprime-community/fprime-workshop-led-blinker/blob/main/docs/initial-integration.md?plain=1#L18-L23

**Comment by LeStarch** [comment]
@thomas-bc we should add defaults to all yes/no questions including:

1. Use existing venv?
2. Add to cmake?
3. Generate implementations?
4. Any found in UT section.

**Comment by LeStarch** [comment]
Fixed!
