### ISSUE TITLE
Move Events Before Telemetry

### ISSUE THREAD

**Issue by LeStarch** [fprime-community/fprime-workshop-led-blinker#4]
Events should be moved before, and discussed before covering Telemetry.  The rationale:

1. Telemetry requires special "packet definitions", which is just one more distraction before seeing F´ run
2. Events show a uniqueness to F´ whereas telemetry is fairly standard.

**Comment by LeStarch** [comment]
Steps:
- Move telemetry to "Events" portion of components part II
- Move events to "Tlemetry" portion of comps part I
- Move "add telem packet defintions" as note under telemetry section of comps II

**Comment by kevin-f-ortega** [comment]
Addressed in here https://github.com/fprime-community/fprime-workshop-led-blinker/pull/13
