### ISSUE TITLE
Led-blinker tutorial ambiguity 

### ISSUE THREAD

**Issue by HoldMyTyr** [fprime-community/fprime-workshop-led-blinker#50]
In the LED Blinker: Unit Testing tutorial section, located at https://fprime-community.github.io/fprime-workshop-led-blinker/docs/unit-testing.html has a section worded strangely. The paragraph in question is "Next, update the CMakeLists.txt file in your led-blinker/Components/Led directory to add those files to the list of unit-test source files. Include a module dependency of Os for the mutex we used. That section should look like this:" However the following code should replace a previous section of code at the top of this page we had rather than simply adding onto the current code section. This is not made clear with the current instructions on the webpage. The code to be replaced is:
set(UT_SOURCE_FILES
    "${CMAKE_CURRENT_LIST_DIR}/Led.fpp"
)
set(UT_AUTO_HELPERS ON) # Additional Unit-Test autocoding
register_fprime_ut()

and is to be replaced with:
set(UT_SOURCE_FILES
    "${CMAKE_CURRENT_LIST_DIR}/Led.fpp"
    "${CMAKE_CURRENT_LIST_DIR}/test/ut/TestMain.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/test/ut/Tester.cpp"
)
set(UT_MOD_DEPS
    Os
)
set(UT_AUTO_HELPERS ON) # Additional Unit-Test autocoding
register_fprime_ut()

**Comment by HoldMyTyr** [comment]
Additionally, the tests we created on the same page are never run. The code provided should be placed in the TestMain.cpp file in order to properly run the test case. 

TEST(Nominal, testBlinkInterval) { 
    Components::Tester tester;
    tester.testBlinkInterval();
}

**Comment by thomas-bc** [comment]
Addressed by https://github.com/fprime-community/fprime-workshop-led-blinker/pull/49
