### ISSUE TITLE
Directory specification for using fprime-util build in Testing the Topology section

### ISSUE THREAD

**Issue by Feniren** [fprime-community/fprime-workshop-led-blinker#62]
In the Testing the Topology section of LED Blinker: Initial Component Integration, you are instructed to run fprime-util build before running fprime-gds --ip-client. However, following from the Add Led Component To The Deployment section it is most likely that the user is in the /LedBlinker/Top directory. Because of this, running fprime-util build work, but running fprime-gds --ip-client will create an application that does not have the led component commands. It would be helpful if the Testing the Topology section specified that you are not to build in the /Top directory.

**Comment by LeStarch** [comment]
Good advice!

**Comment by LeStarch** [comment]
@kevin-f-ortega could you fix this one too?  Should be quick!
